use tictactoe::play_game;

fn main() {
    let mut board: [&str; 9] = ["1", "2", "3", "4", "5", "6", "7", "8", "9"];

    // TODO:
    // 1. Check if a player wins and handle...
    // 2. Check if no more play and handle...
    // 3. Prevent overwriting of previous play...
    // 4. Write Test...
    play_game(&mut board);
}
